services:
  app:
    build: .
    container_name: school-library-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

  app-seed:
    build: .
    image: sl-app:latest
    env_file:
      - .env
    volumes:
      - .:/app
    command: python scripts/seed_mongodb.py
    restart: "no"
    profiles:
      - seed
    # Run with: docker compose run --rm app-seed
